language: python
python:
    - 3.4
    - 3.3
    - 2.7
sudo: false
env:
install:
    - pip install . coveralls -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=jupyter_nbformat jupyter_nbformat
after_success:
    - coveralls
